Repository sequentech/election-portal, pull requests merged in 2023-06, with the labels that each got.

#197 Bump socket.io-parser from 4.0.4 to 4.2.3
  package.json
  yarn.lock
Labels: dependencies

#198 Bump socket.io-parser from 4.0.4 to 4.2.3 (#197)
  package.json
  yarn.lock
Labels: dependencies

#199 Alternative Auth methods support
  app.js
Labels: enhancement

#200 Alternative Auth methods support (#199)
  app.js
Labels: enhancement

#201 ✨ Countdown until logout
  SequentConfig.js
Labels: enhancement, breaking-change

#203 `master` branch should be using `master` version number and not `8.0.0`
  Gruntfile.js
  SequentConfig.js
  SequentPluginsConfig.js
  index.html
  package.json
Labels: bug
