Repository sequentech/election-portal, pull requests merged in 2024-02, with the labels that each got.

#221 🐞 default translation appears when switching language for the first time
  Gruntfile.js
  app.js
  avElection/public-controller/public-controller.js
Labels: bug

#222 🐞 default translation appears when switching language for the first time
  Gruntfile.js
  app.js
  avElection/public-controller/public-controller.js
Labels: bug

#223 🐞 default translation appears when switching language for the first time
  app.js
  avElection/layouts/simple-question-directive/simple-question-directive.js
  avElection/results-directive/results-directive.js
Labels: bug

#224 🐞 default translation appears when switching language for the first time (#223)
  app.js
  avElection/layouts/simple-question-directive/simple-question-directive.js
  avElection/results-directive/results-directive.js
Labels: bug

#226 ✨ login page: no redirection if election hasn't started (#225)
  avElection/public-controller/public-controller.js
Labels: enhancement

#227 Security dependencies update
  package.json
Labels: dependencies

#228 Security dependencies update (#227)
  package.json
Labels: dependencies

#229 Security dependencies update
  package.json
  yarn.lock
Labels: dependencies

#230 Security dependencies update (#229)
  package.json
  yarn.lock
Labels: dependencies

#231 ✨ Fix WCAG Issues and create new report
  avElection/layouts/default-election-directive/default-election-directive.html
  locales/en.json
  locales/es.json
Labels: enhancement
